In [ ]:
# 查看当前挂载的数据集目录
!ls /home/kesci/input/

In [ ]:
# 查看个人持久化工作区文件
!ls /home/kesci/work/

In [1]:
# 查看当前kernerl下的package
# !pip list --format=columns

In [2]:
# 显示cell运行时长
%load_ext klab-autotime

> 代码来自于《Python数据科学手册》的代码复现。

# NumPy 入门

查看版本

In [3]:
import numpy
numpy.__version__

'1.14.2'

time: 10.3 ms


大多数人都习惯使用np左右别名导入NumPy
例如：

In [4]:
import numpy as np

time: 834 µs


## Python的数据类型
Python的数据类型是动态推断的，这是我认为比C语言灵活的地方。
例如：
```
x = 4
x = "four"
```

## 列表

In [11]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

time: 2.64 ms


In [22]:
type(L[2])

int

time: 3.34 ms


In [18]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

time: 2.62 ms


In [21]:
type(L2[0])

str

time: 2.29 ms


In [23]:
L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

time: 2.92 ms


## 固定数组

In [24]:
import array
L = list(range(10))
A = array.array('i', L)
A 

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

time: 3.11 ms


numpy包中的ndarray对象也达到该效果

## 从Python列表创建数组
利用np.array从Python列表创建数组：
整型数组

In [25]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

time: 4.02 ms


numpy要求数组必须包含同一类型的数据，若是不同则向上转换

In [26]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

time: 3.02 ms


还可以设置固定的数据类型，用dtype关键字：

In [27]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

time: 2.86 ms


numpy数组是可以多维的，下面是列表初始化多维数组的一种

In [28]:
# 嵌套列表构造的多维数组
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

time: 2.89 ms


## 从头创建数组
面对大型数组的时候， 利用numpy内置的方法从头创建数组是一种更搞笑的方法。一下是示例：

创建一个长度为10 的数组， 数组的值都是0

In [29]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

time: 2.86 ms


In [33]:
# 创建一个3 x　５的浮点数组，数组的值都是１
np.ones((3, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

time: 2.82 ms


In [32]:
# 创建一个 3 X 5 的浮点型数组，数组的值都是3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

time: 3.07 ms


创建一个线性序列数组

In [34]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

time: 2.58 ms



创建一个5个元素的数组，这2个数均匀的分配到0~1

In [36]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

time: 3.11 ms


创建一个 3 X 3 的，在0~1均匀分布的随级数组组成的数组

In [37]:
np.random.random((3, 3))

array([[0.06894943, 0.8685184 , 0.46117051],
       [0.22624146, 0.93017847, 0.84763557],
       [0.81386909, 0.41591071, 0.94192142]])

time: 2.99 ms


创建一个3X3的，均值为0， 彼标准差为1的正态随机数组

In [38]:
np.random.normal(0, 1, (3, 3))

array([[ 0.84262482, -0.68791928, -0.22379997],
       [-0.13376647,  0.68875823,  0.40452055],
       [ 0.75179075, -0.08039557,  0.45733357]])

time: 3.27 ms


创建一个 3 X 3 的，[0, 10)区间随机整型数组

In [39]:
np.random.randint(0, 10, (3, 3))

array([[6, 7, 7],
       [5, 0, 1],
       [4, 7, 4]])

time: 3.87 ms


创建一个 3 X 3 的单位矩阵

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

time: 3.84 ms


创建一个由3个整型数组成为初始化的数组数组的值是内存空间的任意值

In [41]:
np.empty(3)

array([1., 1., 1.])

time: 2.71 ms


**NumPy标准数据类型**

| 数据类型 | 描述 |
|:------ | :--- |
|bool_ | 布尔值(真、 True 或假、False), 用一个字节存储|
|int_ | 默认整型(类似于C语言中的long,通常情况下是int64或int32)|
|intc | 同C语言的int相同(通常是int32或int64)|
|intp | 用作索引的整型(和C语言的ssize _t相同，通常情况下是int32或int64)|
|int8 | 字节(byte, 范围从-128到127)|
|int16 | 整型(范围从-32768到32767)|
|int32 | 整型(范围从-2147483648到2147483647)|
|int64 | 整型(范围从-9223372036854775808到9223372036854775807)|
|uint8 | 无符号整型(范围从0到255)|
|uint16 | 无符号整型(范围从0到65535)|
|uint32 | 无符号整型(范围从0到4294967295)|
|uint64 | 无符号整型(范围从0到18446744073709551615)|
|float_ | float64的简化形式|
|float16 | 半精度浮点型:符号比特位，5比特位指数(exponent), 10 比特位尾数(mantissa)|
|float32 | 单精度浮点型:符号比特位，8比特位指数，23 比特位尾数|
|float64 | 双精度浮点型:符号比特位，11比特位指数，52 比特位尾数|
|complex_ | complex128的简化形式|
|complex64 | 复数，由两个32位浮点数表示|
|complex128 | 复数，由两个64位浮点数表示|





# 数组基础

先介绍几类基本的数组操作
* 数组的属性
	确定数组的大小、形状、存储大小，数据类型
* 数据的索引
	获取和设置组各个元素的值
* 数组的切分
	在大的数组中获取或设置更小的子数组。
* 数组的变形
	改变给定数组的形状。
* 数组的拼接和分裂
	将多个数组合并为一个，以及讲一个数组分裂成多个

## NumPy数组的属性

先介绍一些有用的数组，定义三个随机的数组：一个一维数组、一个二维数组和一个三维数组。将用NumPy的随机生成器设置一组种子值，以确保每次程序执行时都可以生成同样的随机数组：

In [1]:
import numpy as np

np.random.seed(0) # 设置随机数种子
x1 = np.random.randint(10, size = 6) # 一维数组
x2 = np.random.randint(10, size = (3, 4)) # 二维数组
x3 = np.random.randint(10, size = (3, 4, 5)) # 三维数组

每个数组都有ndim（数组的维度）:
shape（数组每个维度的大小）:
size（数组的总大小）:
数组的数据类型：
每个数组元素字节大小的itemsize：
数组总字节大小：

In [2]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("x3 dtype:", x3.dtype)
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int64
x3 itemsize: 8 bytes
x3 nbytes: 480 bytes


一般来说可以认为： nbytes = itemsize * size

## 数组索引

和Python的列表一样，在一维数组中，可以使用括号指定索引第`i`个值（从0开始计数）

In [4]:
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
x1[1]

0

In [8]:
x1[4]

7

为了获取数组的末尾索引，可以用负值索引：

In [11]:
x1[-1]

9

In [13]:
x1[-4]

3

在多维数组中，可以使用分隔的索引元素获取元素：

In [14]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
x2[0, 0]

3

In [16]:
x2[2, 0]

1

In [17]:
x2[2, -3]

6

也可以用来修改元素值：

In [19]:
x2[0, 0] = 12

In [20]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

和python列表不同，NumPy数组是固定类型的

In [21]:
x1[0] = 3.1234 # 将会自动截断成整型，而且不会有任何的提醒
x1

array([3, 0, 3, 3, 7, 9])

## 数组切片

之前一个是获取单个的数组元素，也可以利用切片(slice)来获取数组的子数组，切片用冒号(:)表示，NumPy切片的语法和Python列表的标准切片语法相同。
语法:
`X = [start : stop : step]`

如果三个参数都没有指定，则默认值 start = 0, stop = 维度的大小(size of dimension), step = 1.

### 一维子数组

In [23]:
x = np.arange(10)

In [24]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

截取前五个元素

In [25]:
x[: 5]

array([0, 1, 2, 3, 4])

后五个元素

In [26]:
x[5 :]

array([5, 6, 7, 8, 9])

中间的子数组

In [27]:
x[4 : 7]

array([4, 5, 6])

每隔一个元素

In [28]:
x[: : 2]

array([0, 2, 4, 6, 8])

每隔一个元素，索引从0开始

In [29]:
x[1 : : 2]

array([1, 3, 5, 7, 9])

所有元素逆序

In [33]:
x[: : -1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

从索引5开始，每隔一个元素逆序

In [31]:
x[5 : : -2]

array([5, 3, 1])

### 多维数组

In [34]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

显示两行，三列

In [35]:
x2[: 2,  : 3]

array([[12,  5,  2],
       [ 7,  6,  8]])

所有行，每隔一列

In [36]:
x2[: 3, :: 2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

子数组的维度也是可以逆序的：

In [37]:
x2[:: -1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

### 获取数组行和列

将索引和切片结合起来可以实现获取单行或者单列。

x2的第一列

In [39]:
print(x2[:, 0])

[12  7  1]


In [41]:
x2[:, 0]

array([12,  7,  1])

x2的第一行

In [43]:
print(x2[0, :])

[12  5  2  4]


在获取行时，可以省略空的切片：

In [44]:
print(x2[0]) # 等同于x2[0, :]

[12  5  2  4]


### 非副本视图的子数组

In [45]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


从中抽取一个 2 X 2 的子数组：

In [48]:
print(x2[: 2, : 2])

[[12  5]
 [ 7  6]]


In [51]:
x2_sub = x2[: 2, : 2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [54]:
x2_sub[0, 0] = 99
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


这种方式是非常有用的，在处理非常大的数据是， 可以获取或者处理这些数据集的片段，而不是复制底层的数据缓存

### 创建数组的副本

In [56]:
x2_sub_copy = x2[: 2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


这个和视图不同的是修改这个子数组，原始的数组也不会发生改变

In [60]:
x2_sub_copy[0, 0] = 10
print(x2_sub_copy)

[[10  5]
 [ 7  6]]


In [61]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## 数组的变形

数组变换最灵活的方式是通过reshape()函数来实现的。
例如，如果你希望将数字1-9放入一个3X3的矩阵中，可以采用如下方法：

In [1]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


另一个常见的变形模式是将一个以为数组转变为二维的行或列的矩阵。也可以通过reshape方法来实现，或者更简单的在一个切片操作中利用newaxis关键字：

In [2]:
x = np.array([1, 2, 3])
# 通过变形获得行向量
x.reshape((1, 3))

array([[1, 2, 3]])

In [3]:
# 通过newaxis获得行向量
x[np.newaxis, :]

array([[1, 2, 3]])

In [4]:
# 通过变形获得的列向量
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [5]:
# 通过newaxis获得列向量
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## 数组拼接和分裂

### 数组的拼接 
拼接和连接NumPy中的两个数组主要由np.concatenate、np.vstack和np.hstack

In [6]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

可以同时拼接多个数组：

In [8]:
z = [55, 99, 299]
print(np.concatenate([x, y, z]))

[  1   2   3   3   2   1  55  99 299]


也可以拼接二维数组：

In [12]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

沿第一个轴拼接

In [13]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

沿第二个轴拼接

In [14]:
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

沿着固定维度处理数组时，使用np.vstack（垂直栈）和np.hstack（水平栈）函数会更简洁：

In [15]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])

# 垂直栈数组
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [16]:
# 水平栈数组
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

np.dstack将沿第三个维度拼接数组。

### 数组的分裂

分裂可以通过np.split、np.hsplit和np.vsplit函数来实现。

In [18]:
x = [2, 3, 4, 5, 6, 8]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[2 3 4] [5 6] [8]


In [20]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [22]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


np.dsplit分割三维数组

# 通用函数

NumPy数组的计算有时候很快有时候很慢，利用`向量化`是使其变快的关键，通常是通过其通用函数(usunc)中实现的

## 慢循环

In [3]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
values = np.random.randint(1, 10, size = 5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [4]:
big_array = np.random.randint(1, 100, size = 1000000)
%timeit compute_reciprocals(big_array)

2.22 s ± 7.74 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## 通用函数介绍

NumPy为很多类型的操作提供了非常方便的、静态类型的、可编译程序的借口，也被称为向量操作，比较以下两个结果：

In [6]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


如果计算一个大数组的运行时间，可以看到它的完成时间比Python循环话费的时间更短：

In [8]:
%timeit (1.0 / big_array)

3.76 ms ± 19.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


通用函数可以对数组进行运算的：

In [9]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

也可以进行多维数组的运算：

In [12]:
x = np.arange(16).reshape((4, 4))
2 ** x

array([[    1,     2,     4,     8],
       [   16,    32,    64,   128],
       [  256,   512,  1024,  2048],
       [ 4096,  8192, 16384, 32768]])

## 探索通用函数

### 数组的计算

In [16]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) 

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


还有球负数，指数和模运算的一元通用函数：

In [18]:
print("-x     =", -x)
print("x ** 2 =", x ** 2)
print("x % 2  =", x % 2)

-x     = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2  = [0 1 0 1]


封装器

In [19]:
np.add(x, 3)

array([3, 4, 5, 6])

NumPy实现算数运算符

| 运算符 | 对应的通用函数 | 描述 |
| :---- | :----------- | :-- |
| + | np.add | 加法运算
| - | np.subtract | 减法运算
| - | np.negative | 负数运算
| * | np.multiply | 乘法运算
| / | np.divide | 除法运算
| // | np.floor_divide | 地板除法运算
| ** | np.power | 指数运算
| % | np.mod | 模 、余数

### 绝对值

Python的内置绝对值函数

In [20]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

NumPy通云函数是np.absolute,也可以用别名np.abs：

In [21]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [22]:
np.abs(x)

array([2, 1, 0, 1, 2])

这个通用函数也可以用来处理复数，档处理复数时候，绝对值返回的是改函数的模：

In [23]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

### 三角函数

In [25]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [26]:
print("theta     =", theta)
print("sin(theta =", np.sin(theta))
print("cos(theta =", np.cos(theta))
print("tan(theta =", np.tan(theta))

theta     = [0.         1.57079633 3.14159265]
sin(theta = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


#### 指数和对数函数

In [27]:
x = [1, 2, 3]
print("x    =", x)
print("e^x  =", np.exp(x))
print("2^x  =", np.exp2(x))
print("3^x  =", np.power(3, x))

x    = [1, 2, 3]
e^x  = [ 2.71828183  7.3890561  20.08553692]
2^x  = [2. 4. 8.]
3^x  = [ 3  9 27]


In [29]:
x = [1, 2, 3, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 3, 4, 10]
ln(x)    = [0.         0.69314718 1.09861229 1.38629436 2.30258509]
log2(x)  = [0.         1.         1.5849625  2.         3.32192809]
log10(x) = [0.         0.30103    0.47712125 0.60205999 1.        ]


对于非常小的书也是非常好的保留精度的

In [30]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


### 专用的通用函数

In [31]:
from scipy import special

In [32]:
# Gamma函数和相关函数
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("li|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
li|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [33]:
# 误差函数，实现及其逆实现
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)    =", special.erf(x))
print("erfc(x)   =", special.erfc(x))
print("erfinc(x) =", special.erfinv(x))

erf(x)    = [0.         0.32862676 0.67780119 0.84270079]
erfc(x)   = [1.         0.67137324 0.32219881 0.15729921]
erfinc(x) = [0.         0.27246271 0.73286908        inf]


## 高级的通用函数特性
### 指定输出

In [36]:
x = np.arange(5)
y = np.empty(5)
print(x)
print(y)
np.multiply(x, 10, out = y)
print(y)

[0 1 2 3 4]
[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323]
[ 0. 10. 20. 30. 40.]


In [37]:
y = np.zeros(10)
print(y)
np.power(2, x, out = y[::2])
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


聚合

In [39]:
x = np.arange(1, 6)
print(x)
np.add.reduce(x)

[1 2 3 4 5]


15

In [40]:
np.multiply.reduce(x)

120

如果需要计算的中间结果，可以使用accumulate

In [41]:
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))

[ 1  3  6 10 15]
[  1   2   6  24 120]


### 外积

In [42]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

## 最小值、最大值和其他值

### 数组值求和

In [45]:
import numpy as np

L = np.random.random(100)
print(L)
sum(L)

[0.99582517 0.12262206 0.87372235 0.54930356 0.22098344 0.42400088
 0.75555836 0.14429492 0.14954931 0.0836442  0.1971993  0.2737172
 0.80664559 0.12795214 0.74832818 0.15328873 0.64007825 0.56112099
 0.99771693 0.59142874 0.1258379  0.26427913 0.21400439 0.56670611
 0.03711501 0.77855492 0.12333906 0.97831986 0.91493149 0.48018112
 0.64199802 0.72634578 0.76189613 0.73617636 0.27554977 0.51399161
 0.31250207 0.51614311 0.33375313 0.07894331 0.05119731 0.93837673
 0.47768444 0.78235034 0.12059267 0.75252218 0.986168   0.31698481
 0.07241729 0.09302211 0.1062065  0.65226978 0.63679941 0.56501659
 0.50732646 0.74612829 0.551229   0.75045644 0.11738258 0.85625695
 0.14358165 0.48963091 0.5616225  0.20271625 0.48569236 0.08226467
 0.8402376  0.21585936 0.62580422 0.09991539 0.43570458 0.54809679
 0.58970373 0.58213233 0.62527206 0.25535607 0.360616   0.78876727
 0.45002187 0.86374775 0.22482424 0.82505022 0.41668365 0.3928502
 0.68689608 0.43244067 0.70490621 0.01694    0.22488122 0.648324

46.63620765216888

In [46]:
np.sum(L)

46.63620765216889

In [50]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

96.9 ms ± 527 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
442 µs ± 1.81 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### 最大值最小值

In [51]:
min(big_array), max(big_array)

(1.890489775835391e-07, 0.9999993031657582)

In [52]:
np.min(big_array), np.max(big_array)

(1.890489775835391e-07, 0.9999993031657582)

In [53]:
%timeit min(big_array)
%timeit np.min(big_array)

75.7 ms ± 575 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
360 µs ± 1.59 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [54]:
print(big_array.min(), big_array.max(), big_array.sum())

1.890489775835391e-07 0.9999993031657582 499766.70505024446


多维度聚合

In [56]:
M = np.random.random((3, 4))
print(M)

[[0.30954309 0.43679222 0.86953481 0.11957794]
 [0.56586598 0.44348423 0.66370113 0.6035834 ]
 [0.29607204 0.72450252 0.44696634 0.6116325 ]]


In [57]:
M.sum()

6.091256195578881

找每一列最小

In [58]:
M.min(axis=0)

array([0.29607204, 0.43679222, 0.44696634, 0.11957794])

找每一行最大

In [59]:
M.max(axis=1)

array([0.86953481, 0.66370113, 0.72450252])

示例：美国总统的身高是多少

In [5]:
!head -4 /home/kesci/input/Handbook6828/president_heights.csv

order,name,height(cm)
1,George Washington,189
2,John Adams,170
3,Thomas Jefferson,189


In [6]:
import pandas as pd
data = pd.read_csv('/home/kesci/input/Handbook6828/president_heights.csv')
heights = np.array(data['height(cm)'])
print(heights)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


In [7]:
print("Mean height:       ", heights.mean())
print("Standard deviation:", heights.std())
print("Minimun height:    ", heights.min())
print("Maximun height:    ", heights.max())

Mean height:        179.73809523809524
Standard deviation: 6.931843442745892
Minimun height:     163
Maximun height:     193


In [8]:
print("25th percentile:  ", np.percentile(heights, 25))
print("Median:           ", np.median(heights))
print("75th percentile:  ", np.percentile(heights, 75))

25th percentile:   174.25
Median:            182.0
75th percentile:   183.0


In [11]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn; seaborn.set() # 设置绘图风格

In [13]:
plt.hist(heights)
plt.title('Height Distribution of US Presidents')
plt.xlabel('height(cm)')
plt.ylabel('number')
plt.show()

<Figure size 432x288 with 1 Axes>

# 广播

In [14]:
import numpy as np
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [15]:
a + 5

array([5, 6, 7])

In [16]:
M = np.ones((3, 3))
print(M)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [18]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [19]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [20]:
M = np.ones((2, 3))
a = np.arange(3)

In [21]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [23]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

In [24]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [25]:
a 

array([[0],
       [1],
       [2]])

In [26]:
M = np.ones((3, 2))
a = np.arange(3)

In [30]:
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [33]:
print(M)
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]


In [32]:
a[:, np.newaxis].shape

(3, 1)

In [35]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

广播规则对于任意二进制通用函数都是适用的

In [36]:
np.logaddexp(M, a[:, np.newaxis])

array([[1.31326169, 1.31326169],
       [1.69314718, 1.69314718],
       [2.31326169, 2.31326169]])

In [38]:
X = np.random.random((10, 3))
Xmean = X.mean(0)
Xmean

array([0.44962305, 0.53916304, 0.40801379])

In [40]:
X_centered = X -Xmean
X_centered.mean(0)

array([-1.11022302e-17,  6.66133815e-17,  5.55111512e-17])

In [41]:
x = np.linspace(0, 5, 50)
y = np.linspace(0, 5, 50)[:, np.newaxis]
z = np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x)

In [44]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.imshow(z, origin='lower', extent=[0, 5, 0, 5], cmap='viridis')
plt.colorbar();

<Figure size 432x288 with 2 Axes>

# 比较、掩码和布尔逻辑

## 示例：统计下雨天数

In [1]:
import numpy as ny
import pandas as pd

# 利用Pandas抽取降雨量，放入一个NumPy数组
rainfall = pd.read_csv('/home/kesci/input/Handbook6828/Seattle2014.csv')['PRCP'].values
inches = rainfall / 254
inches.shape

(365,)

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn; seaborn.set()

plt.hist(inches, 40);

<Figure size 432x288 with 1 Axes>

##   类比操作

In [3]:
x = np.array([1, 2, 3, 4, 5])
x < 3

array([ True,  True, False, False, False])

In [4]:
x > 3

array([False, False, False,  True,  True])

In [5]:
(2 * x)  == (x ** 2)

array([False,  True, False, False, False])

In [6]:
np.equal(x, 2)

array([False,  True, False, False, False])

In [7]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [8]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [9]:
np.less(x, 6)

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

### 操作布尔数组

In [10]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


统计记录个数

In [11]:
# 有多少个值小于6？
np.count_nonzero(x < 6)

8

In [12]:
np.sum(x < 6)

8

In [13]:
# 每行有多少值小于6
np.sum(x < 6, axis=1)

array([4, 2, 2])

有没有值大于8

In [14]:
np.any(x > 8)

True

有没有值小于0

In [15]:
np.any(x < 0)

False

是否所有的值都小于10？

In [16]:

np.all(x < 10)

True

是否所有的值都等于6

In [17]:
np.all(x == 6)

False

是否所有的行都等于8

In [18]:
np.all(x < 8, axis=1)

array([ True, False,  True])

统计降水量在0.5英寸和1英寸之间的天数

In [19]:
np.sum((inches > 0.5) & (inches < 1))

29

In [20]:
np.sum(~((inches <= 0.5) | (inches >= 1)))

29

In [21]:
print("Number days without rain:       ", np.sum(inches == 0))
print("Number days with rain:          ", np.sum(inches != 0))
print("Days with more than 0.5 inches: ", np.sum(inches > 0.5))
print("Rainy day with < 0.2 inches:    ", np.sum((inches > 0) & (inches < 0.2)))

Number days without rain:        215
Number days with rain:           150
Days with more than 0.5 inches:  37
Rainy day with < 0.2 inches:     75


将布尔数组作为掩码

In [22]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [23]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])

为所有下雨天创建一个掩码

In [24]:
rainy = (inches > 0)

构建一个包含整个夏季日期的掩码（6.21是172天）

In [25]:
summer = (np.arange(365) - 172 < 90) & (np.arange(365) - 172 > 0)


In [26]:
print("Median precip on rainy days in 2014:    ", np.median(inches[rainy]))
print("Median precip on summer days in 2014:   ", np.median(inches[summer]))
print("Maximum precip on summer days in 2014:  ", np.max(inches[summer]))
print("Median precip non-summer rainy days:    ", np.median(inches[rainy & ~summer]))

Median precip on rainy days in 2014:     0.19488188976377951
Median precip on summer days in 2014:    0.0
Maximum precip on summer days in 2014:   0.8503937007874016
Median precip non-summer rainy days:     0.20078740157480315


索引

In [1]:
import numpy as np

In [2]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [3]:
[x[3], x[7], x[2]]

[71, 86, 14]

In [4]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [6]:
ind = np.array([[3, 7], [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [7]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [10]:
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [11]:
row[:, np.newaxis] * col

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

组合索引

In [12]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
X[2, [2, 0, 1]]

array([10,  8,  9])

In [14]:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [15]:
mask = np.array([1, 0, 1, 0], dtype=bool)
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

示例：选择随机数

In [16]:
mean = [0, 0]
cov = [[1, 2], [2, 5]]
X = rand.multivariate_normal(mean, cov, 100)
X.shape

(100, 2)

In [10]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn; seaborn.set()
plt.scatter(X[:, 0], X[:, 1]);

NameError: name 'X' is not defined

In [18]:
indices = np.random.choice(X.shape[0], 20, replace=False)
indices

array([63, 84, 67, 98, 40, 88, 27, 36, 15, 95, 65,  4, 24, 57, 10, 34, 69,
       93, 51, 68])

In [19]:
selection = X[indices]
selection.shape

(20, 2)

In [20]:
plt.scatter(X[:, 0], X[:, 1], alpha=0.3)
plt.scatter(selection[:, 0], selection[:, 1], facecolor='none', edgecolor='b', s=200)

<Figure size 432x288 with 1 Axes>

用索引修改值

In [1]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99

In [2]:
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [3]:
x[i] -= 10
print(x)

[ 0 89 89  3 89  5  6  7 89  9]


In [4]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
i = [2, 3, 3, 4, 4, 4, 4]
x[i] += 1
print(x)

[6. 0. 1. 1. 1. 0. 0. 0. 0. 0.]


累加

In [7]:
x = np.zeros(10)
np.add.at(x, i, 1)
print(x)

[0. 0. 1. 2. 4. 0. 0. 0. 0. 0.]


示例：数据区间划分

In [8]:
np.random.seed(42)
x = np.random.random(100)

bins = np.linspace(-5, 5, 20)
counts = np.zeros_like(bins)

i = np.searchsorted(bins, x)

np.add.at(counts, i, 1)

In [11]:
plt.plot(bins, counts, linestyle='steps');

<Figure size 432x288 with 1 Axes>

In [12]:
plt.hist(x, bins, histtype='step');

<Figure size 432x288 with 1 Axes>

# 数组的排序

选择排序

In [13]:
import numpy as np

def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x
    
x = np.array([2, 1, 4, 3, 5])
selection_sort(x)

array([1, 2, 3, 4, 5])

In [14]:
def bogosort(x):
    while np.any(x[:-1] > x[1:]):
        np.random.shuffle(x)
    return x

x = np.array([2, 1, 4, 3, 5])
bogosort(x)

array([1, 2, 3, 4, 5])

NumPy中的快速排序

In [15]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [16]:
x.sort()
print(x)

[1 2 3 4 5]


返回索引值

In [17]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [18]:
x[i]

array([1, 2, 3, 4, 5])

沿着行或列排序

In [19]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


对X的每一个行排序

In [20]:
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

对X的每一列排序

In [21]:
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

部分排序

找到第三小的，放在最左边右边则任意排序

In [22]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [23]:
np.partition(X, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

示例：`K`个近邻

In [24]:
X = rand.rand(10, 2)

In [26]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn; seaborn.set()
plt.scatter(X[:, 0], X[:, 1], s=100);

<Figure size 432x288 with 1 Axes>

计算矩阵的平方距离

In [32]:
dist_sq = np.sum((X[:, np.newaxis, :] - X[np.newaxis, :, :]) ** 2, axis=-1)

In [29]:
differences = X[:, np.newaxis, :] - X[np.newaxis, :, :]
differences.shape

(10, 10, 2)

In [30]:
sq_differences = differences ** 2
sq_differences.shape

(10, 10, 2)

In [31]:
dist_sq = sq_differences(-1)
dist_sq.shape

TypeError: 'numpy.ndarray' object is not callable

In [33]:
dist_sq.diagonal()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
nearest = np.argsort(dist_sq, axis=1)
print(nearest)

[[0 3 9 7 1 4 2 5 6 8]
 [1 4 7 9 3 6 8 5 0 2]
 [2 1 4 6 3 0 8 9 7 5]
 [3 9 7 0 1 4 5 8 6 2]
 [4 1 8 5 6 7 9 3 0 2]
 [5 8 6 4 1 7 9 3 2 0]
 [6 8 5 4 1 7 9 3 2 0]
 [7 9 3 1 4 0 5 8 6 2]
 [8 5 6 4 1 7 9 3 2 0]
 [9 7 3 0 1 4 5 8 6 2]]


In [35]:
K = 2
nearest_partition = np.argpartition(dist_sq, K + 1, axis=1)

In [37]:
plt.scatter(X[:, 0], X[:, 1], s=100)

K = 2 

for i in range(x.shape[0]):
    for j in nearest_partition[i, :K+1]:
        plt.plot(*zip(X[j], X[i]), color='black')

<Figure size 432x288 with 1 Axes>

# 结构化数组

常规操作

In [1]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [2]:
x = np.zeros(4, dtype=int)

使用复合数据结构的结构化数组

In [3]:
data = np.zeros(4, dtype={'names' : ('name', 'age', 'weight'), 'formats' : ('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


U10表示“长度不超过10的Unicode字符串”， i4表示“4字节（32比特）整型”， f8表示“8字节（64比特）浮点型”

将列表数组放入数组中：

In [4]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


获取所有名字

In [5]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

获取数据的第一行

In [6]:
data[0]

('Alice', 25, 55.)

获取最后一行的名字

In [7]:
data[-1]['name']

'Doug'

获取年龄小于30岁的人的名字

In [8]:
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

生成结构化数组

In [9]:
np.dtype({'names' : ('name', 'age', 'weight'), 'formats' : ('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

数值类型可以用Python类型或NumPy的dtype类型指定：

In [10]:
np.dtype({'names' : ('name', 'age', 'weight'), 'formats' : ((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

复合类型也可以是元组列表：

In [11]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [12]:
np.dtype('S10, i4, f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

Numpy的数据类型

| NumPy数据类型符号 | 描述 |                  示例 |
| :---- | :----- | :------ |
| 'b' | 字节型 | np.dtype('b') |
| 'i' | 有符号整型 | np.dtype('i4') == np.int32 |
| 'u' | 无符号整型 | np.dtype('u1') == np.uint8 |
| 'f' | 浮点型 | np.dtype('f8') == np.int64 |
| 'c' | 复数浮点型 | np.dtype('c16') == np.complex128 |
| 'S'、 'a' | 字符串 | np.dtype('S5') |
| 'U' | Unicode编码字符串 | np.dtype('U') == np.str_ |
| 'V' | 原生数据，raw data (空，void) | np.dtype('V') == np.void |